opt_in_rules:
- anyobject_protocol
- closing_brace
- closure_body_length
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- contains_over_filter_count
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- cyclomatic_complexity
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- discouraged_optional_boolean
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- enum_case_associated_values_count
- explicit_init
- explicit_self
- fallthrough
- fatal_error_message
- file_length
- file_name
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- generic_type_name
- identical_operands
- identifier_name
- implicit_getter
- implicitly_unwrapped_optional
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- multiline_arguments
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- private_action
- private_outlet
- protocol_property_accessors_order
- raw_value_for_camel_cased_codable_enum
- reduce_boolean
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_type_annotation
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- sorted_first_last
- sorted_imports
- statement_position
- static_operator
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_closure
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_declaration
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- void_return
- weak_delegate

trailing_whitespace:
    ignores_empty_lines: true

excluded:
- Carthage
- Pods

force_unwrapping: error

line_length:
    warning: 200
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true
function_body_length: 45
closure_body_length: 25
type_name:
    min_length: 3
    max_length: 50
function_parameter_count: 6
type_body_length: 401
file_length:
    warning: 401
    error: 401
    ignore_comment_only_lines: false
cyclomatic_complexity: 10
enum_case_associated_values_count: 6
identifier_name:
    min_length: 3
    max_length: 50
nesting:
    type_level: 2
large_tuple: 5
warning_threshold: 1
reporter: "xcode"
